#pragma once

#include "headset/headset.h"

typedef struct {
  bool (*HeadsetInit)(HeadsetConfig* config);
  void (*HeadsetDestroy)(void);
  bool (*HeadsetConnect)(void);
  bool (*HeadsetIsConnected)(void);
  const char* (*HeadsetGetName)(void);
  const char* (*HeadsetGetDriver)(void);
  void (*HeadsetGetFeatures)(HeadsetFeatures* features);
  uint32_t (*HeadsetGetLayerLimit)(void);
  bool (*HeadsetIsSeated)(void);
  bool (*HeadsetStart)(void);
  void (*HeadsetStop)(void);
  bool (*HeadsetIsActive)(void);
  uint32_t (*HeadsetGetSessionGeneration)(void);
  bool (*HeadsetIsMainSessionVisible)(void);
  bool (*HeadsetIsVisible)(bool* main);
  bool (*HeadsetIsFocused)(void);
  bool (*HeadsetIsMounted)(void);
  bool (*HeadsetPollEvents)(void);
  bool (*HeadsetUpdate)(void);
  void (*HeadsetGetDisplayDimensions)(uint32_t* width, uint32_t* height);
  float* (*HeadsetGetRefreshRates)(uint32_t* count);
  float (*HeadsetGetRefreshRate)(void);
  bool (*HeadsetSetRefreshRate)(float refreshRate);
  void (*HeadsetGetFoveation)(FoveationLevel* level, bool* dynamic);
  bool (*HeadsetSetFoveation)(FoveationLevel level, bool dynamic);
  bool (*HeadsetIsHDR)(void);
  bool (*HeadsetIsPassthroughSupported)(PassthroughMode mode);
  PassthroughMode (*HeadsetGetPassthrough)(void);
  bool (*HeadsetSetPassthrough)(PassthroughMode mode);
  uint32_t (*HeadsetGetViewCount)(void);
  bool (*HeadsetGetViewPose)(uint32_t view, float* position, float* orientation);
  bool (*HeadsetGetViewAngles)(uint32_t view, float* left, float* right, float* up, float* down);
  void (*HeadsetGetClipDistance)(float* clipNear, float* clipFar);
  void (*HeadsetSetClipDistance)(float clipNear, float clipFar);
  void (*HeadsetGetBoundsDimensions)(float* width, float* depth);
  bool (*HeadsetGetHandPose)(Side side, HandPose type, float* position, float* orientation);
  bool (*HeadsetGetPose)(Device device, float* position, float* orientation);
  bool (*HeadsetGetVelocity)(Device device, float* velocity, float* angularVelocity);
  bool (*HeadsetIsDown)(Device device, DeviceButton button, bool* down, bool* changed);
  bool (*HeadsetIsTouched)(Device device, DeviceButton button, bool* touched);
  bool (*HeadsetGetAxis)(Device device, DeviceAxis axis, float* value);
  bool (*HeadsetGetSkeleton)(Device device, float* poses, SkeletonSource* source);
  bool (*HeadsetGetBattery)(Device device, float* level, bool* charging);
  bool (*HeadsetVibrate)(Device device, float strength, float duration, float frequency);
  void (*HeadsetStopVibration)(Device device);
  uint64_t* (*HeadsetGetModelKeys)(uint32_t* count);
  struct ModelData* (*HeadsetNewModelData)(uint64_t key);
  bool (*HeadsetGetModelPose)(struct Model* model, float* position, float* orientation);
  bool (*HeadsetAnimate)(struct Model* model);
  struct Texture* (*HeadsetSetBackground)(uint32_t width, uint32_t height, uint32_t layers);
  Layer** (*HeadsetGetLayers)(uint32_t* count, bool* main);
  bool (*HeadsetSetLayers)(Layer** layers, uint32_t count, bool main);
  bool (*HeadsetGetTexture)(struct Texture** texture);
  bool (*HeadsetGetPass)(struct Pass** pass);
  bool (*HeadsetSubmit)(void);
  void (*HeadsetSetPose)(Device device, float* position, float* orientation);
  void (*HeadsetSetButton)(Device device, DeviceButton button, bool down);
  Layer* (*LayerCreate)(const LayerInfo* info);
  void (*LayerDestroy)(void* ref);
  Device (*LayerGetOrigin)(Layer* layer);
  void (*LayerSetOrigin)(Layer* layer, Device device);
  void (*LayerGetPose)(Layer* layer, float* position, float* orientation);
  void (*LayerSetPose)(Layer* layer, float* position, float* orientation);
  void (*LayerGetDimensions)(Layer* layer, float* width, float* height);
  void (*LayerSetDimensions)(Layer* layer, float width, float height);
  float (*LayerGetCurve)(Layer* layer);
  bool (*LayerSetCurve)(Layer* layer, float curve);
  void (*LayerGetColor)(Layer* layer, float color[4]);
  void (*LayerSetColor)(Layer* layer, float color[4]);
  void (*LayerGetViewport)(Layer* layer, int32_t* viewport);
  void (*LayerSetViewport)(Layer* layer, int32_t* viewport);
  struct Texture* (*LayerGetTexture)(Layer* layer);
  struct Pass* (*LayerGetPass)(Layer* layer);
  void (*HeadsetGetVulkanPhysicalDevice)(void* instance, uintptr_t physicalDevice);
  uint32_t (*HeadsetCreateVulkanInstance)(void* instanceCreateInfo, void* allocator, uintptr_t instance, void* getInstanceProcAddr);
  uint32_t (*HeadsetCreateVulkanDevice)(void* instance, void* deviceCreateInfo, void* allocatoor, uintptr_t device, void* getInstanceProcAddr);
  double (*HeadsetGetDisplayTime)(void);
  double (*HeadsetGetDisplayPeriod)(void);
  double (*HeadsetGetDeltaTime)(void);
  bool (*HeadsetGetDepthTexture)(struct Texture** texture);
} HeadsetOps;

extern const HeadsetOps lovrHeadsetOpenXROps;
